# Generated by Django 5.2.6 on 2025-09-16 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LanguagesSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.BigIntegerField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.language')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('stars', models.BigIntegerField(default=0)),
                ('forks', models.BigIntegerField(default=0)),
                ('watchers', models.BigIntegerField(default=0)),
                ('isFork', models.BooleanField(default=False)),
                ('isArchived', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(blank=True, null=True)),
                ('pushedAt', models.DateTimeField(blank=True, null=True)),
                ('license', models.CharField(blank=True, max_length=255, null=True)),
                ('languages', models.ManyToManyField(related_name='repositories', through='task.LanguagesSize', to='task.language')),
                ('primaryLanguage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_repos', to='task.language')),
            ],
        ),
        migrations.AddField(
            model_name='languagessize',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.repository'),
        ),
        migrations.CreateModel(
            name='TopicsStars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.BigIntegerField()),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.repository')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.topic')),
            ],
            options={
                'unique_together': {('repo', 'topic')},
            },
        ),
        migrations.AddField(
            model_name='repository',
            name='topics',
            field=models.ManyToManyField(related_name='repositories', through='task.TopicsStars', to='task.topic'),
        ),
        migrations.AlterUniqueTogether(
            name='languagessize',
            unique_together={('repo', 'language')},
        ),
    ]
