# Generated by Django 5.2.6 on 2025-09-15 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('stars', models.BigIntegerField()),
                ('forks', models.BigIntegerField()),
                ('watchers', models.BigIntegerField()),
                ('is_fork', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('primary_languages', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('pushed_at', models.DateTimeField()),
                ('lisense', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('size', models.BigIntegerField()),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='task.repository')),
            ],
        ),
    ]
